### ISSUE TITLE
lack of asm ?

### ISSUE THREAD

**Issue by aorjoa** [bloomberg/spark-flow#3]
When i used `spark-shell` and add `spark-flow` library only via CLI
```
$ ./bin/spark-shell --jars /Users/AorJoa/Repository/spark-flow/target/scala-2.11/spark-flow_2.11-0.1.0-SNAPSHOT.jar
```
i found error when run example like this
```
scala> import com.bloomberg.sparkflow
import com.bloomberg.sparkflow

scala> val numbers = sparkflow.parallelize(1 to 10)
numbers: com.bloomberg.sparkflow.dc.DC[Int] = com.bloomberg.sparkflow.dc.ParallelCollectionDC@3add5e17

scala> val filtered = numbers.filter(_ < 3).checkpoint()
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
  at com.bloomberg.sparkflow.serialization.Hashing$.hashClass(Hashing.scala:53)
  at com.bloomberg.sparkflow.dc.DC.filter(DC.scala:64)
  ... 48 elided
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 50 more
```
and i figue out i can fix with `asm` by download directly from Maven Central Repo and used in `--jars` parameters of `spark-shell`
```
scala> import com.bloomberg.sparkflow
import com.bloomberg.sparkflow

scala> val numbers = sparkflow.parallelize(1 to 10)
numbers: com.bloomberg.sparkflow.dc.DC[Int] = com.bloomberg.sparkflow.dc.ParallelCollectionDC@b34c7c9

scala> val filtered = numbers.filter(_ < 3).checkpoint()
Using spark-flow's default log4j profile: com/bloomberg/sparkflow/log4j-defaults.properties
filtered: com.bloomberg.sparkflow.dc.DC[Int] = com.bloomberg.sparkflow.dc.DatasetTransformDC@7791ff50

scala> val doubled = filtered.map(_ * 2)
doubled: com.bloomberg.sparkflow.dc.DC[Int] = com.bloomberg.sparkflow.dc.DatasetTransformDC@1d1c63af

scala> println(doubled.getRDD(sc).sum())
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
6.0              
```
this issue just for discuss about and solution for newbie like me :)

**Comment by nimbusgo** [comment]
Yes, this is an issue caused by not creating an assembly jar. When you add the sparkflow jar it has the classes contained within sparkflow, but not its dependencies. If you were to make an sbt project for example and add sparkflow as a dependency sbt would grab the dependencies for sparkflow as well and put all of them together if you were to make an assembly jar. If you included just that jar when starting spark shell it should work.

I'll add this to the todos, to add an sbt assembly step so an assembly jar can be produced which will work when including it in the spark shell.

As a sidenote, this is similar to how spark works, when running spark you have to have the spark assembly jar on the classpath which has all its transient dependencies. If you just add the spark-core jar it won't work. However, when listing spark-core as a dependency in either maven or sbt then during the build they'll track down the transient dependencies.

**Comment by aorjoa** [comment]
Thank you @nimbusgo your command make me clear. However, sometime i use fat jar in my IntelliJ project its lead to dependency conflict in this case i edit `build.sbt` but i have no ideea when `spark-shell` pass by parameter `--jars`
ps. sorry i'm newbie and not influence in English
